### ISSUE TITLE
Add support for boolean fields

### ISSUE THREAD

**Issue by schobster** [dfurtado/dataclass-csv#12]
#  Description
Support various string representations of `bool` values. 

# Use Case 
I'd like to use `dataclass-csv` as part of a data pipeline which imports data from a CSV intermediate format into PostgreSQL. Currently any non-null boolean value is parsed as `True`, which prevents me from using this nice package.  

# Proposed solution
```
    def _parse_bool_value(self, bool_value):
        """Parses `str` representation of a boolean value to a `bool`. Case-insensitive.
        Values parsed as True: 'yes', 'true', 't', 'y', '1'
        Values parsed as False: 'no', 'false', 'f', 'n', '0
        All other values(including empty/NULL) parsed as None.
        """
        return str2bool(bool_value)
```
We can use this in `_process_row()`. This leverages a very lightweight package called `str2bool` and I put a little wrapper around it just so we can have a unit test around this parsing in case we decide to change the implementation later.

If you'd rather not add this dependency, we could re-implement `str2bool` pretty easily.

I've got this ready to roll locally, so feel free to assign this one to me and I can get a PR submitted shortly. 

Btw, I'm really liking this package and `dataclasses` in general and would be glad to help out more in the future. Thanks!

**Comment by dfurtado** [comment]
Hi @schobster !!

Thank you so much for opening this issue. It was actually on my plans to add support for boolean values, so your PR will come in the right time!

I think it is a great idea and I believe that it would be better to implement something similar to `str2bool` instead of adding it as a dependency. The reason is that I wanted to keep this lib very clean using only what is available in the standard library.

Please, submit the PR and I will have a look at it soon as I can.

Thank you!! :+1:

**Comment by dfurtado** [comment]
Hi @schobster 

I've added a few comments on your PR. It looks great!

**Comment by schobster** [comment]
Thank you for your feedback and the prompt reply, @dfurtado ! 

I've addressed the comments, with the main change being removing the `str2bool` dependency per your suggestion. Just let me know if I've missed anything, or if you'd like any further changes.

**Comment by dfurtado** [comment]
Merged to master.
