### ISSUE TITLE
Automatically generate candidate dataclass

### ISSUE THREAD

**Issue by nealmcb** [dfurtado/dataclass-csv#36]
When just exploring lots of different csv files, it would be very handy to have an optional way to scan a csv file and generate a dataclass that would work with it.

It could start off just reading row headers and using them to come up with legal attribute names.

Next, automatically generating attribute types by analyzing the contents of each column would also be handy.

If that funtionality could be provided as module functions and called from other software, it could eventually be possible to start playing with csv files that you run across, and have the module automatically read a csv in and provide access to the rows as objects which could be introspected.

**Comment by dfurtado** [comment]
Hi @nealmcb 

Thanks for creating this issue! I really appreciate it :+1: 

It would be a very nice feature for sure but I'm thinking about some difficulties, for example, reading the column name in the CSV file and then trying to figure it out a property name (following Python naming conventions) for the `dataclass` would be very hard.

It would be easier If the column name is separated by spaces, eg: `street name` could be `street_name` and so on. In cases where the name doesn't have space, eg: `streetname`, then it would be a bit trickier.

Guessing the types would also be difficult since columns might contain "10" or 10 and it would be hard to say if the property should be defined as `int` or `str`.

My vision when I created the `dataclass-csv` was to provide a reader for `dataclasses` the same way we have dict reader in the standard library, following the UNIX philosophy, doing just one thing and do it well. This feature would be really cool to have but it is getting into the code generation field and a bit out of the scope of this project.

**Comment by tewe** [comment]
In my experience there are two ways to approach CSV, exploratory and production-ready. Only the former allows guessing types. What distinguishes this library from the included batteries is that it checks types, so it belongs to the latter approach.

But I like your idea, as a separate utility. It could use Pandas to guess the types and generate the dataclass as a string of Python code. Maybe 150 LOC?

**Comment by dfurtado** [comment]
I agree! That could definitely be a separate library that could be used together with `dataclass-csv`.

**Comment by dfurtado** [comment]
Closing this one since we agreed that his functionality belong to its own package.
